"""fase6_tabla_servicios

Revision ID: 245b89ade11a
Revises: 851bc6a56013
Create Date: 2026-04-22 19:17:23.094104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245b89ade11a'
down_revision: Union[str, None] = '851bc6a56013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('medico', 'comedor', 'bibliobus', 'venta_ambulante', 'otro', name='tiposervicio'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('horario', sa.Text(), nullable=True),
    sa.Column('informacion_adicional', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicios_id'), 'servicios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_servicios_id'), table_name='servicios')
    op.drop_table('servicios')
    # ### end Alembic commands ###
