"""fase7_tabla_anuncios

Revision ID: 6a6b6002dec1
Revises: 245b89ade11a
Create Date: 2026-04-22 19:32:30.655881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6b6002dec1'
down_revision: Union[str, None] = '245b89ade11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('mascota_perdida', 'compra_venta', 'objeto_perdido', 'otro', name='tipoanuncio'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('contacto', sa.String(length=300), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_caducidad', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anuncios_id'), 'anuncios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anuncios_id'), table_name='anuncios')
    op.drop_table('anuncios')
    # ### end Alembic commands ###
